apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.service.name}}-2
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}-2
  template:
    metadata:
      labels:
        app: {{.Values.service.name}}-2
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: waitForDns
          image: "alpine:3.6"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - 'sleep 30'
      containers:
      - name: {{.Values.service.name}} 
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: 27017
        - containerPort: 28017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
        volumeMounts:
        - name: mongo-persistent-2
          mountPath: /data/db
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", 'printf "use admin\ndb.shutdownServer()" | mongo']
      volumes:
      - name: mongo-persistent-2
        persistentVolumeClaim:
          claimName: "{{ .Values.service.name }}-pvc-2"
