apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  labels:
    failure-domain.beta.kubernetes.io/region: {{ .Values.pv1.region }} 
    failure-domain.beta.kubernetes.io/zone: {{ .Values.pv1.zone }} 
    provisioned-for: {{.Values.service.name}}-1
  name: {{ .Values.pv1.name }} 
  namespace: "default"
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: {{ .Values.fsType }} 
    volumeID: {{ .Values.pv1.volumeID }} 
  capacity:
    storage: {{ .Values.storageGi }} 
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.pv1.claimName }} 
    namespace: default
  persistentVolumeReclaimPolicy: Retain
