{{- $values :=  .Values }}

{{- range $values.pvs }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  labels:
    failure-domain.beta.kubernetes.io/region: {{ .region }}
    failure-domain.beta.kubernetes.io/zone: {{ .zone }}
    provisioned-for: {{ $values.service.name }}-{{ . }}
  name: {{ .name }}
  namespace: "default"
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: {{ $values.fsType }}
    volumeID: {{ .volumeID }}
  capacity:
    storage: {{ $values.storageGi }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .claimName }}
    namespace: default
  persistentVolumeReclaimPolicy: Retain
{{- end }}
