{{- $values :=  .Values }}

{{- range $index, $pv :=  $values.pvs }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  labels:
    failure-domain.beta.kubernetes.io/region: {{ $pv.region }}
    failure-domain.beta.kubernetes.io/zone: {{ $pv.zone }}
    provisioned-for: {{ $values.service.name }}-{{ $index }}
  name: {{ $pv.name }}
  namespace: "default"
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: {{ $values.fsType }}
    volumeID: {{ $pv.volumeID }}
  capacity:
    storage: {{ $values.storageGi }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ $pv.claimName }}
    namespace: default
  persistentVolumeReclaimPolicy: Retain
{{- end }}
