{{- range tuple "0" "1" "2" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  labels:
    failure-domain.beta.kubernetes.io/region: {{ .Values.pv{{ . }}.region }}
    failure-domain.beta.kubernetes.io/zone: {{ .Values.pv{{ . }}.zone }}
    provisioned-for: {{.Values.service.name}}-{{ . }}
  name: {{ .Values.pv{{ . }}.name }}
  namespace: "default"
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: {{ .Values.fsType }}
    volumeID: {{ .Values.pv{{ . }}.volumeID }}
  capacity:
    storage: {{ .Values.storageGi }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.pv{{ . }}.claimName }}
    namespace: default
  persistentVolumeReclaimPolicy: Retain
{{- end }}
