kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.name }}-pvc-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageGi }}
  selector:
    matchLabels:
      provisioned-for: {{.Values.service.name}}-2
