{{- $values :=  .Values }}

{{- range tuple "0" "1" "2" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ $values.service.name }}-pvc-{{ . }}"
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: "{{ $values.service.name}}-{{ . }}-vol"
  storageClassName: ebs-sc
  resources:
    requests:
      storage: {{ $values.storageGi }}
{{- end }}