{{- range tuple "0" "1" "2" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.name }}-pvc-{{ . }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageGi }}
  selector:
    matchLabels:
      provisioned-for: {{.Values.service.name}}-{{ . }}
{{- end }}
