{{- $values :=  .Values }}

{{- range tuple "0" "1" "2" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ $values.service.name }}-pvc-{{ . }}"
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      provisioned-for: {{ $values.service.name}}-{{ . }}
{{- end }}
