{{- $values :=  .Values }}
{{- $chart := .Chart }}

{{- range tuple "0" "1" "2" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.service.name }}-{{ . }}
  labels:
    chart: "{{ $chart.Name | trunc 63 }}"
    chartVersion: "{{ $chart.Version | trunc 63 }}"
    app: {{ $values.service.name }}-{{ . }}
    visualize: "true"
  annotations:
    # https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L56
    # create endpoints for unready pods - mongo needs to resolve the cluster member addresses on startup
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: work
    port: 27017
    targetPort: 27017
  - name: admin
    port: 28017
    targetPort: 28017
  clusterIP: None
  selector:
    app: {{ $values.service.name }}-{{ . }}
{{- end }}
