apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}-1
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{.Values.service.name}}-1
    visualize: "true"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: work
    port: 27017
    targetPort: 27017
  - name: admin
    port: 28017
    targetPort: 28017
  selector:
    app: {{ .Values.service.name }}-1
