apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{.Values.service.name}} 
    visualize: "true"
spec:
  ports:
  - name: work
    port: 27017
    targetPort: 27017
  - name: admin
    port: 28017
    targetPort: 28017
  clusterIP: None
  selector:
    app: {{ .Values.service.name }}
